//TODO: remove dummy data only for dev purpose

export const dummyDashboardData = {
  stats: {
    borrowedBooks: 145,
    borrowedBooksDelta: -2,
    totalUsers: 317,
    totalUsersDelta: 4,
    totalBooks: 163,
    totalBooksDelta: 2,
  },
  barrowRequests: [
    {
      id: "br1",
      title: "Inside Evil: Inside Evil Series, Book 1",
      author: "Rachel Heng",
      genre: ["Strategic", "Fantasy"],
      user: "Darrell Stewards",
      date: "12/01/24",
      cover: "inside-evil.jpg",
    },
    {
      id: "br2",
      title: "Jayne Castle - People in Glass Houses",
      author: "Rachel Heng",
      genre: ["Strategic", "Fantasy"],
      user: "Darrell Stewards",
      date: "12/01/24",
      cover: "jayne-castle.jpg",
    },
    {
      id: "br3",
      title: "The Great Reclamation: A Novel",
      author: "Rachel Heng",
      genre: ["Strategic", "Fantasy"],
      user: "Darrell Stewards",
      date: "12/01/24",
      cover: "reclamation.jpg",
    },
    {
      id: "br4",
      title: "The Future of Us",
      author: "Jay Asher",
      genre: ["Romance", "Sci-Fi"],
      user: "Jane Cooper",
      date: "11/30/24",
      cover: "future-us.jpg",
    },
    {
      id: "br5",
      title: "Atomic Habits",
      author: "James Clear",
      genre: ["Self-help", "Strategy"],
      user: "Marc Atenson",
      date: "11/28/24",
      cover: "atomic-habits.jpg",
    },
    {
      id: "br6",
      title: "Project Hail Mary",
      author: "Andy Weir",
      genre: ["Sci-Fi"],
      user: "Ian Warren",
      date: "11/25/24",
      cover: "hail-mary.jpg",
    },
    {
      id: "br7",
      title: "The Midnight Library",
      author: "Matt Haig",
      genre: ["Fiction", "Philosophy"],
      user: "Susan Drake",
      date: "11/22/24",
      cover: "midnight-library.jpg",
    },
    {
      id: "br8",
      title: "The Silent Patient",
      author: "Alex Michaelides",
      genre: ["Thriller"],
      user: "Ronald Richards",
      date: "11/20/24",
      cover: "silent-patient.jpg",
    },
    {
      id: "br9",
      title: "Dune",
      author: "Frank Herbert",
      genre: ["Sci-Fi", "Adventure"],
      user: "Marc Atenson",
      date: "11/18/24",
      cover: "dune.jpg",
    },
    {
      id: "br10",
      title: "Educated",
      author: "Tara Westover",
      genre: ["Memoir"],
      user: "Jane Cooper",
      date: "11/15/24",
      cover: "educated.jpg",
    },
  ],
  recentBooks: [
    {
      id: "rb1",
      title: "The Great Reclamation: A Novel",
      author: "Rachel Heng",
      genre: ["Strategic", "Fantasy"],
      date: "12/01/24",
      cover: "reclamation.jpg",
    },
    {
      id: "rb2",
      title: "Inside Evil: Inside Evil Series, Book 1",
      author: "Rachel Heng",
      genre: ["Strategic", "Fantasy"],
      date: "12/01/24",
      cover: "inside-evil.jpg",
    },
    {
      id: "rb3",
      title: "Jayne Castle - People in Glass Houses",
      author: "Rachel Heng",
      genre: ["Strategic", "Fantasy"],
      date: "12/01/24",
      cover: "jayne-castle.jpg",
    },
    {
      id: "rb4",
      title: "The Power of Habit",
      author: "Charles Duhigg",
      genre: ["Self-help"],
      date: "11/28/24",
      cover: "power-habit.jpg",
    },
    {
      id: "rb5",
      title: "1984",
      author: "George Orwell",
      genre: ["Dystopian"],
      date: "11/25/24",
      cover: "1984.jpg",
    },
    {
      id: "rb6",
      title: "Becoming",
      author: "Michelle Obama",
      genre: ["Biography"],
      date: "11/22/24",
      cover: "becoming.jpg",
    },
    {
      id: "rb7",
      title: "The Alchemist",
      author: "Paulo Coelho",
      genre: ["Fiction", "Philosophy"],
      date: "11/20/24",
      cover: "alchemist.jpg",
    },
    {
      id: "rb8",
      title: "Sapiens: A Brief History of Humankind",
      author: "Yuval Noah Harari",
      genre: ["History", "Science"],
      date: "11/18/24",
      cover: "sapiens.jpg",
    },
    {
      id: "rb9",
      title: "Thinking, Fast and Slow",
      author: "Daniel Kahneman",
      genre: ["Psychology"],
      date: "11/15/24",
      cover: "thinking-fast-slow.jpg",
    },
    {
      id: "rb10",
      title: "Norwegian Wood",
      author: "Haruki Murakami",
      genre: ["Romance", "Drama"],
      date: "11/12/24",
      cover: "norwegian-wood.jpg",
    },
  ],
  accountRequests: [
    {
      id: "ar1",
      name: "Marc Atenson",
      email: "marcinnne@gmail.com",
      avatar: "marc.jpg",
    },
    {
      id: "ar2",
      name: "Susan Drake",
      email: "contact@susandrake.com",
      avatar: "susan.jpg",
    },
    {
      id: "ar3",
      name: "Ronald Richards",
      email: "ronaldrichard@gmail.com",
      avatar: "ronald.jpg",
    },
    {
      id: "ar4",
      name: "Jane Cooper",
      email: "janecooper@protonmail.com",
      avatar: "jane.jpg",
    },
    {
      id: "ar5",
      name: "Ian Warren",
      email: "wadewarren@mail.co",
      avatar: "ian.jpg",
    },
    {
      id: "ar6",
      name: "Darrell Steward",
      email: "darrellsteward@gmail.com",
      avatar: "darrell.jpg",
    },
    {
      id: "ar7",
      name: "Ella Stone",
      email: "ella.stone@mail.io",
      avatar: "ella.jpg",
    },
    {
      id: "ar8",
      name: "Tommy Rivers",
      email: "tommy.r@fastmail.com",
      avatar: "tommy.jpg",
    },
    {
      id: "ar9",
      name: "Linda Green",
      email: "lindagreen@domain.org",
      avatar: "linda.jpg",
    },
    {
      id: "ar10",
      name: "Oscar Knight",
      email: "osk.knight@bookmail.com",
      avatar: "oscar.jpg",
    },
  ],
};
